#!/bin/bash
# Display all running processes with the correct format and hierarchy

ps -eo user,pid,pcpu,pmem,vsz,rss,tty,stat,lstart,time,cmd --forest \
| awk 'NR==1 { $6="STARTED"; $11="CMD"; print } NR>1 { print }'
