#!/usr/bin/env bash
# Displays all processes with user, full start time, and command

ps -eo user,lstart,cmd --no-headers | awk '{
    printf "%s %s %s %s %s %s\n", $1, $2, $3, $4, $5, substr($0, index($0,$7))
}'
