#!/usr/bin/env bash
# A Bash script that displays only the lines containing the word "bash" from the process list
# shellcheck disable=SC2009

ps -eo user,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,cmd --forest | grep bash
