#!/usr/bin/env bash
# Stops the 4-to_infinity_and_beyond process using bash built-in kill (not /bin/kill or killall)

pid=$(pgrep -f 4-to_infinity_and_beyond)

if [ -n "$pid" ]; then
  builtin kill "$pid"
  exit 2
else
  exit 0
fi
