#!/usr/bin/env bash
# Find 7-highlander PID(s) and send SIGTERM to them

pids=$(pgrep -f './7-highlander')

if [[ -z "$pids" ]]; then
  echo "No 7-highlander process found."
  exit 1
fi

for pid in $pids; do
  kill -TERM "$pid"
done
