#!/usr/bin/env bash
# Infinite loop printing a message; on SIGTERM prints "I am invincible!!!"

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
