#!/usr/bin/env bash
# Forcefully kill all 7-highlander processes using SIGKILL

# Get all PIDs of 7-highlander
pids=$(pgrep -f 7-highlander)

if [ -n "$pids" ]; then
  # Kill all found PIDs properly
  # Use 'kill -9' on each PID separately
  for pid in $pids; do
    builtin kill -9 "$pid"
  done
  exit 2
else
  exit 0
fi
